export const LOAD_ALL_STORIES = 'proj/App/LOAD_ALL_STORIES'
export const LOAD_ALL_STORIES_SUCCESS = 'proj/App/LOAD_ALL_STORIES_SUCCESS'
export const LOAD_ALL_STORIES_ERROR = 'proj/App/LOAD_ALL_STORIES_ERROR'
