export const LOAD_ALL_STORIES = 'LoadDialog/LOAD_ALL_STORIES'
export const LOAD_ALL_STORIES_SUCCESS = 'LoadDialog/LOAD_ALL_STORIES_SUCCESS'
export const LOAD_ALL_STORIES_ERROR = 'LoadDialog/LOAD_ALL_STORIES_ERROR'
