/*
 *
 * Graph constants
 *
 */

export const DEFAULT_ACTION = 'Graph/DEFAULT_ACTION'
export const SET_LISTENING = 'Graph/SET_LISTENING'
export const SET_SELECTED_NODE = 'Graph/SET_SELECTED_NODE'
export const SET_SELECTED_LINK = 'Graph/SET_SELECTED_LINK'
export const SET_DIMENSIONS = 'Graph/SET_DIMENSIONS'
export const INCREMENT_NODE_COUNTER = 'Graph/INCREMENT_NODE_COUNTER'
export const INCREMENT_LINK_COUNTER = 'Graph/INCREMENT_LINK_COUNTER'
export const SET_LINKING_NODE = 'Graph/SET_LINKING_NODE'
export const SET_MOUSEDOWN_NODE = 'Graph/SET_MOUSEDOWN_NODE'
export const SET_MOUSEDOWN_LINK = 'Graph/SET_MOUSEDOWN_LINK'
export const SET_SHOULD_REDRAW = 'Graph/SET_SHOULD_REDRAW'
